api_platform:
    title: '%env(API_TITLE)%'
    description: '%env(API_DESCRIPTION)%'
    version: '%env(API_VERSION)%'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    swagger:
        api_keys:
            apiKey:
                name: X-AUTH-TOKEN
                type: header
    collection:
        pagination:
            enabled: false
